spring:
  profiles:
    active:
    - dev
---
server:
  port: 8201
spring:
  application:
    name: microservicecloud-client-config-dev
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservice-dept-8001 #自定义初始化实例的ID
    prefer-ip-address: true #访问路径可以显示IP
---
server:
  port: 8202
spring:
  application:
    name: microservicecloud-client-config-test
  profiles: test
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservice-dept-8001 #自定义初始化实例的ID
    prefer-ip-address: true #访问路径可以显示IP


 
