spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.xml  #mybatis配置文件
  mapper-locations: classpath:mybatis/mapper/**/*.xml  #mybatis映射文件
  type-aliases-package: com.staryea.entities  #mybatis对应的实体类目录


spring:
  application:
    name: microservice-provider-dept
  profiles: dept

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=UTF-8&&serverTimezone=UTC
    username: root
    password: 123456
    dbcp2:
      max-idle: 10
      min-idle: 5
      max-wait-millis: 60000
      initial-size: 5
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservice-dept-8001 #自定义初始化实例的ID
    prefer-ip-address: true #访问路径可以显示IP





info: # 展示前台页面点击微服务名称需要显示的内容
  app.name: staryea-microservice-dept-8001
  company.name: starya
  build.artifactId: $project.artifactId$
  bulid.verison: $project.verison$

---
server:
  port: 8003
mybatis:
  config-location: classpath:mybatis/mybatis.xml  #mybatis配置文件
  mapper-locations: classpath:mybatis/mapper/**/*.xml  #mybatis映射文件
  type-aliases-package: com.staryea.entities  #mybatis对应的实体类目录


spring:
  application:
    name: microservice-provider-dept
  profiles: dept-8003

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/e3mall?useUnicode=true&characterEncoding=UTF-8&&serverTimezone=UTC
    username: root
    password: 123456
    dbcp2:
      max-idle: 10
      min-idle: 5
      max-wait-millis: 60000
      initial-size: 5
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservice-dept-8002 #自定义初始化实例的ID
    prefer-ip-address: true #访问路径可以显示IP





info: # 展示前台页面点击微服务名称需要显示的内容
  app.name: staryea-microservice-dept-8002
  company.name: starya
  build.artifactId: $project.artifactId$
  bulid.verison: $project.verison$


---
server:
  port: 80
spring:
  application:
    name: microservice-consumer-dept-feign
  profiles: dept-feign
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservice-consumer-feign-dept
    prefer-ip-address: true

# 开启熔断
feign:
  hystrix:
    enabled: true

---
server:
  port: 9527
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-zuul
    prefer-ip-address: true
spring:
  application:
    name: microservicecloud-zuul-gateway
  profiles: zuul-dept
#  profiles:
#    active:

zuul:
  routes:
    mydept.serviceId: microservice-provider-dept
    mydept.path: /mydept/**
  ignored-services: microservice-provider-dept #禁止使用真实路径访问 禁用多个用 "*"
  prefix: /staryea  #所有请求路径加上前缀
#  sensitiveHeaders: "*" #过滤所有的head信息


